sudo: required

services:
- docker

language: java
dist: trusty

jdk:
- openjdk11

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - DOCKER_IMAGE=nimbostratuz/bikeshare-rental
  - IMAGE_VERSION=0.1

script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE:$IMAGE_VERSION" -t "$DOCKER_IMAGE:latest" .

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE:$IMAGE_VERSION" && docker push "$DOCKER_IMAGE:latest"
