sudo: required

services:
- docker

language: java
dist: trusty

jdk:
- openjdk11

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - DOCKER_IMAGE=nimbostratuz/bikeshare-rental
  - IMAGE_VERSION=0.11

script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE:$IMAGE_VERSION" .

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE:$IMAGE_VERSION"

branches:
  only:
  - master
