version: '3.7'

services:
  db-pgsql:
    image: postgres:alpine
    restart: always
    ports:
    - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikeshare-rental
