version: '3.7'

services:
  db-pgsql:
    image: postgres:alpine
    restart: always
    ports:
    - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikeshare-rental
  bikeshare-rental:
    image: nimbostratuz/bikeshare-rental:latest
    ports:
    - 8081:8080
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://db-pgsql:5433/bikeshare-rental
#      KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://bikeshare-rental.db.bikeshare:5433/bikeshare-rental
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
    depends_on:
    - db-pgsql
    - etcd
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
    - "2379:2379"
    command: >-
      /usr/local/bin/etcd
      -name node1
      -advertise-client-urls http://etcd:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster node1=http://etcd:2380
      -cors="*"

networks:
  default:
    external:
      name: bikeshare
