kumuluzee:
  name: bikeshare-rental
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/BikeshareRentalDS
    connection-url: jdbc:postgresql://localhost:5433/bikeshare-rental
    username: postgres
    password: postgres
    max-pool-size: 20

    config:
      etcd:
        hosts: http://localhost:2380

    discovery:
      etcd:
        hosts: http://localhost:2380

    health:
      logs:
        enabled: true
        level: FINE
        period-s: 1
      servlet:
        mapping: /health
        enabled: true
      checks:
        data-source-health-check:
          jndi-name: jdbc/BikeshareRentalDS
        etcd-health-check:
          connection-url: http://localhost:2380/health

  app-properties:
    external-services:
      enabled: false
    rest-config:
      string-property: value